### PR TITLE
Fix problems with argument parsing and Ansible 2.1

### LINKED ISSUE #64: Errors with ansible 2.1
I'' getting errors like:
With ansible 2.1
al: [desa-wl12c-1.edisa.com]: FAILED! => {"changed": false, "failed": true, "module_stderFile \"/tmp/ansible_wnslMv/ansible_module_xml.py\", line 424, in <module>\r\n    main()\r\n main\r\n    get_element_text(x, xpath, namespaces, module)\r\n  File \"/tmp/ansible_wnslMv/at is_node(tree, xpath, namespaces):\r\n  File \"/tmp/ansible_wnslMv/ansible_module_xml.py\",ces):\r\n  File \"/tmp/ansible_wnslMv/ansible_module_xml.py\", line 154, in xpath_matches\r\.etree.pyx\", line 2091, in lxml.etree._ElementTree.xpath (src/lxml/lxml.etree.c:53358)\r\n r.__init__ (src/lxml/lxml.etree.c:133440)\r\n  File \"xpath.pxi\", line 276, in lxml.etree.XFile \"xpath.pxi\", line 148, in lxml.etree._XPathEvaluatorBase.__init__ (src/lxml/lxml.etreContext.__init__ (src/lxml/lxml.etree.c:130211)\r\n  File \"extensions.pxi\", line 82, in lxalueError: need more than 1 value to unpack\r\n", "msg": "MODULE FAILURE", "parsed": false}

### PR DESCRIPTION
**Pull request by mss**
This fixes #64 and was cherry-picked from @h0nIg's pull request #65.

### CODE REVIEW

**Comment by cmprescott** [comment]
Thanks!

**Comment by mss** [comment]
Can you roll a 0.4 release with that fix and the other changes from master?

**Comment by cmprescott** [comment]
I'll try to take a look at the other stuff for the 0.4 release in the next day or two. 

I have to think about one of the features. I'm not sure I should allow creating new xml files. I worry that others might mistakenly use this module instead of templating.

**Comment by h0nIg** [comment]
@cmprescott which feature are you talking about? there is no feature to create a new xml file

**Comment by mss** [comment]
I just saw that you already tagged 0.3.3 with the fix for 2.1 and the fixes for empty values. Those are the ones I care about :-)

**Pull request merged**
