### PR TITLE
Reworked for latest code in master branch

### PR DESCRIPTION
**Pull request by PieterVoet**
I previously submitted this PR, but that failed the verification tests. Shoudl be fine now.

My code adds creation of elements that do not exists, or even create a new XML file if it does not exist, including creating the xpath specified.

### CODE REVIEW

**Comment by cmprescott** [comment]
What Ansible version and OS did you run on locally? Travis throwing  error with `need more than 1 value to unpack`

**Comment by PieterVoet** [comment]
Hi Chris,
 
[root@87797cddd8da tests]# ansible --versionansible 2.1.1.0  config file = /etc/ansible/ansible.cfg  configured module search path = Default w/o overrides[root@87797cddd8da tests]# cat /etc/redhat-release CentOS Linux release 7.2.1511 (Core)  
 
I ran all the tests included in the 'tests' directory...  successfully.  Are there any other tests I can run ?
 
Thanks & have a nice day !
 
pieter.
Thanks & regards, Pieter VoetIBM SWG WebSphere services, the NetherlandsTel: (+31)20-5132041 GSM: 06-53412985 Internet: PieterVoet@nl.ibm.com
 
 
----- Original message -----From: Chris Prescott <notifications@github.com>To: cmprescott/ansible-xml <ansible-xml@noreply.github.com>Cc: Pieter J Voet/Netherlands/IBM@IBMNL, Author <author@noreply.github.com>Subject: Re: [cmprescott/ansible-xml] Reworked for latest code in master branch (#79)Date: Sat, Sep 10, 2016 5:08 AM 
What Ansible version and OS did you run on locally? Travis throwing error with need more than 1 value to unpack
—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

 Tenzij hierboven anders aangegeven: / Unless stated otherwise above:
IBM Nederland B.V.
Gevestigd te Amsterdam
Inschrijving Handelsregister Amsterdam Nr. 33054214

**Comment by dodok1** [comment]
Hello,

in my opinion is the PR mixing two functionalities together - creating file and creating element if doesn't exists.

While I would like to see the second one implemented, 
I perceive the first one out of scope of module, as it cannot handle all aspects of XML definitions. I think it could be replaced by another task for creating from template or copying without forcing rewrite.

**Comment by cmprescott** [comment]
Closed do merge conflict &  agreement with @dodok1. I do not want to expand module's scope to include creating new xml files.

**Pull request closed without merging**
