### PR TITLE
further development, multiple fixes

### PR DESCRIPTION
**Pull request by h0nIg**
done some development:

- add xmlstring output variable (which is used in conjunction with empty file, also fixes https://github.com/cmprescott/ansible-xml/issues/58)
- refactor method signatures, since it is always necessary to use the module parameter (for further development)
- add abort statement at the end to prevent situations with unclear workflow end
- add ability to pretty print only without modification
- added test cases for pretty print only and xmlstring input
- add ability to add/set nested elements
- fix problems with argument parsing and ansible 2.1 (fixes https://github.com/cmprescott/ansible-xml/issues/64)

### CODE REVIEW

**Comment by h0nIg** [comment]
ping @cmprescott

**Comment by h0nIg** [comment]
ping @cmprescott

**Comment by mss** [comment]
I don't think your pull request will be merged like that @h0nIg. You should split it in smaller requests by topic which can be reviewed individually.

**Comment by cmprescott** [comment]
@h0nIg do you mind splitting into more modular PR?

**Comment by h0nIg** [comment]
currently this is not possible, due to time lack. please look at the separated commits, since i created a "structure" and mainly there are only small changes.

if you think there is a problem with a commit, lets discuss this here

**Comment by cmprescott** [comment]
changes merged in version 0.3.4

Broke apart PR. Split 2 new features apart for ease of reviewing. 2.1 fix already pushed to master.

**Pull request closed without merging**
